### ISSUE TITLE
Custom Records

### ISSUE THREAD

**Issue by provsalt** [jackthehack21/JukeBox-pmmp#1]
pretty cool if we can have a disc and it plays a nbs file

**Comment by JaxkDev** [comment]
woah hold you horses, i've only just started the project literally yesterday im currently working on the essentials once i release then everyone can request and report things.
What do you mean by NBS file ?, records are the only things planned right now

**Comment by LeoBdt** [comment]
[songs (2) (2).zip](https://github.com/jackthehack21/JukeBox-pmmp/files/2927367/songs.2.2.zip)
check that

**Comment by JaxkDev** [comment]
At the moment, sounds and their files are handled by client.
Meaning it may not be possible for custom sounds but i will look into Resource packs maybe its something you can do via that.

**Comment by LeoBdt** [comment]
Yes it is. Have a look on ZMusicBox plugin

**Comment by JaxkDev** [comment]
Cant find that, and if theres a plugin for custom music why request it here :)

**Comment by LeoBdt** [comment]
i'm just giving more informations.

https://github.com/BrokenItZAndrei100/ZMusicBox/tree/master/

(ZMusicBox is so laggy as fuck)

**Comment by JaxkDev** [comment]
To clear this up,
ZMusicBox is for NoteBlock specifically because it can play different *NOTES*

JukeBox can only play different sounds specific to a certain list, it cannot play notes and create custom ‘tunes’

It can play the music and a resource pack can change the sounds specific to the music ID
